### PR TITLE
Added support for CSRF (required for 2.2.6)

### PR DESCRIPTION
**Pull request by maxxer**

### CODE REVIEW

**Comment by hydrian** [comment]
Thanks for the commit. I still need to go over it. Some of the changes may have security exposure.. so I may have to alter them.

**Comment by maxxer** [comment]
which changes?

**Comment by hydrian** [comment]
2 things. 

I purposely forced HTTPS connection. This at least guarantees the data transfer is encrypted but not necessarily identified (untrusted certificates). With the changes you made, it allows unencrypted HTTP requests. 

Also don't send login credentials in command line options. If the script is run on an untrusted or misconfigured environment, another user (non-root) could get the pfsense's admin login credentials. Temporarily store the POST data in a file.  Then use wget's '--post-file' option to read post data. This way the data is subject to file permissions.

**Comment by hydrian** [comment]
@maxxer I appreciate the contribution. I've updated the script in a way the better represents my priorities. I'm closing your pull request not because it was bad. It just didn't maintain the goals of this project.

**Pull request closed without merging**
